version: "3"
services:
    backend:
        build: backendFiles/.
        ports:
            - "8070:80"
        volumes:
            - ./imageStorage:/var/www/localhost/htdocs/imgs
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: funpills 
        volumes: 
            - ./mysqlData:/var/lib/mysql
            - ./dbInit:/docker-entrypoint-initdb.d/:ro
    burybot:
        build: buryTelligence/
        tty: true            # Enables pseudo-TTY
        stdin_open: true    

