version: "3"
services:
    backend:
        build: ./SERVICES/WEB_BACKEND/backendFiles/.
        ports:
            - "8070:80"
        volumes:
            - ./data_volumes/imageStorage:/var/www/localhost/htdocs/imgs
        labels:
            service: backend
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: funpills 
        volumes: 
            - ./data_volumes/mysqlData:/var/lib/mysql
            - ./SERVICES/DATABASE/dbInit:/docker-entrypoint-initdb.d/:ro
        labels:
            service: db
    redis:
        image: redis
        container_name: redis_userCnt
        ports:
          - "6379:6379"
    express:
        build: playground/express_server
        labels:
            service: backend
        ports:
            - "90:3001"
        depends_on:
            - redis
    burybot:
        build: ./SERVICES/MISC/buryTelligence/.
        tty: true            # Enables pseudo-TTY
        stdin_open: true
        labels:
            service: bot

